#!/usr/bin/env bash
#
# render.sh — generate stack/docker-compose.yml from stack/.env.
#
# The compose file is generated rather than hand-maintained so that changing the
# agent count or the Docker-in-Docker toggle is a re-render, not an edit.
#
# Two things here are easy to get wrong and expensive to debug:
#
#  1. Every VOLUME the images declare is mapped. The server declares three
#     (datadir, logs, temp) and the full agent declares eight (conf, work,
#     system, temp, logs, tools, plugins, /var/lib/docker). Any left unmapped
#     gets a fresh anonymous volume on every `up`, so agent tool and plugin
#     caches are silently discarded on each restart and dead volumes accumulate.
#
#  2. Both images run as uid 1000 (tcuser / buildagent). Anything that seeds a
#     volume must write as 1000 too, or the server cannot write its own data
#     directory and fails on first boot with a permissions error that does not
#     name the cause.

# Volumes declared by jetbrains/teamcity-server.
TC_SERVER_VOLUMES=(
    'datadir:/data/teamcity_server/datadir'
    'logs:/opt/teamcity/logs'
    'temp:/opt/teamcity/temp'
)

TC_AGENT_VOLUMES=(
    'conf:/data/teamcity_agent/conf'
    'work:/opt/buildagent/work'
    'system:/opt/buildagent/system'
    'temp:/opt/buildagent/temp'
    'logs:/opt/buildagent/logs'
    'tools:/opt/buildagent/tools'
    'plugins:/opt/buildagent/plugins'
)

# The full agent image also declares VOLUME /var/lib/docker, whether or not
# Docker-in-Docker is switched on. Mapping it only in the DinD branch left three
# anonymous volumes behind on a default three-agent stack — precisely the leak
# the explicit mapping exists to prevent. The minimal image does not declare it.
render::_agent_has_docker_volume() {
    [[ $TC_AGENT_IMAGE == full || $TC_AGENT_DOCKER == dind ]]
}

render::validate_config() {
    local ok=0
    validate::stack_name  "$TC_STACK"      || ok=1
    validate::port        "$TC_PORT"       || ok=1
    validate::mem_opts    "$TC_MEM_OPTS"   || ok=1
    validate::timezone    "$TC_TZ"         || ok=1
    TC_ALLOW_EXTRA_AGENTS=1 validate::agent_count "$TC_AGENTS" || ok=1

    if [[ $TC_DB == postgres ]]; then
        validate::db_identifier "$TC_PG_DB"   || ok=1
        validate::db_identifier "$TC_PG_USER" || ok=1
        validate::db_password   "$TC_PG_PASSWORD" || ok=1
    fi

    (( ok == 0 )) || {
        ui::err 'stack/.env failed validation; refusing to render a broken stack.'
        return 1
    }
}

render::compose() {
    render::validate_config || return 1
    mkdir -p "$STACK_DIR"

    {
        render::_header
        printf 'services:\n'
        [[ $TC_DB == postgres ]] && render::_db
        # The seed step runs in both database modes: it also writes
        # internal.properties, which is what auto-authorizes agents.
        render::_datadir_init
        render::_server
        local n
        for (( n = 1; n <= TC_AGENTS; n++ )); do render::_agent "$n"; done
        render::_volumes
    } >"$COMPOSE_FILE"

    # A render bug should surface here, not halfway through an `up`.
    if ! docker compose --file "$COMPOSE_FILE" --project-directory "$STACK_DIR" \
            --env-file "$ENV_FILE" config --quiet 2>/tmp/tc-config-err; then
        ui::err 'The generated compose file is invalid:'
        sed 's/^/        /' /tmp/tc-config-err >&2
        return 1
    fi
}

render::_header() {
    cat <<EOF
# Generated by the TeamCity control console — do not edit.
# Re-render with: ./tc  →  Reconfigure    (or delete this file and re-run ./tc)
#
# Settings live in stack/.env. Editing them there is supported; editing here is
# not, because the next render overwrites it.
#
# No top-level 'version:' key: it is obsolete in Compose v2 and only produces a
# warning on every command.

name: $TC_STACK

EOF
}

render::_db() {
    cat <<EOF
  db:
    image: postgres:${TC_PG_VERSION}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: \${TC_PG_DB}
      POSTGRES_USER: \${TC_PG_USER}
      POSTGRES_PASSWORD: \${TC_PG_PASSWORD}
      TZ: \${TC_TZ}
    # TeamCity's pool is 50 connections and maintenance tasks open more on top.
    # The postgres default of 100 leaves too little headroom once agents and a
    # second node are in play.
    command: ['postgres', '-c', 'max_connections=200']
    volumes:
      # PGDATA is /var/lib/postgresql/data. JetBrains' own compose sample mounts
      # /var/lib/postgresql/\${PG_VERSION}/docker, which is not PGDATA — a stack
      # copied from it looks fine and loses the database on recreate.
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U \${TC_PG_USER} -d \${TC_PG_DB}']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

EOF
}

render::_datadir_init() {
    cat <<EOF
  datadir-init:
    image: alpine:3.22
    # Runs as root, and hands the directory to uid 1000 (tcuser) on the way out.
    #
    # It has to be this way round: a freshly created named volume is owned by
    # root:root, because the alpine image has nothing at this path for Docker to
    # copy ownership from. A uid-1000 init container could not even mkdir in it.
    # The server image only chowns the path at build time, which does not apply
    # to a volume seeded by a different container. So: seed as root, chown last.
    environment:
      TC_DB: \${TC_DB}
      TC_PG_DB: \${TC_PG_DB}
      TC_PG_USER: \${TC_PG_USER}
      TC_PG_PASSWORD: \${TC_PG_PASSWORD}
      TC_JDBC_VERSION: \${TC_JDBC_VERSION}
      TC_AGENT_AUTH_TOKEN: \${TC_AGENT_AUTH_TOKEN}
    volumes:
      - datadir:/data/teamcity_server/datadir
      - jdbc-cache:/cache
      - ./init:/init:ro
    entrypoint: ['/bin/sh', '/init/seed-datadir.sh']
    restart: 'no'

EOF
}

render::_server() {
    local depends
    if [[ $TC_DB == postgres ]]; then
        depends=$(cat <<'EOF'
    depends_on:
      db:
        condition: service_healthy
      datadir-init:
        condition: service_completed_successfully
EOF
)
    else
        depends=$(cat <<'EOF'
    depends_on:
      datadir-init:
        condition: service_completed_successfully
EOF
)
    fi

    cat <<EOF
  server:
    image: jetbrains/teamcity-server:\${TC_VERSION}
    restart: unless-stopped
$depends
    environment:
      TEAMCITY_SERVER_MEM_OPTS: \${TC_MEM_OPTS}
      TZ: \${TC_TZ}
    ports:
      - '\${TC_PORT}:8111'
    volumes:
$(render::_volume_lines TC_SERVER_VOLUMES '')
    healthcheck:
      # curl is present in the image (Ubuntu 24.04 installs it), so this is a
      # real HTTP probe rather than a port check — Tomcat binds 8111 long before
      # TeamCity can serve anything.
      #
      # Deliberately no -f. Until the licence is accepted and an administrator
      # exists, TeamCity answers 503 with a maintenance page; -f would treat that
      # as a failure and mark a perfectly healthy server unhealthy for as long as
      # first-run setup takes. Answering HTTP at all is the useful signal here.
      test: ['CMD', 'curl', '-sS', '-o', '/dev/null', '--max-time', '5', 'http://localhost:8111/login.html']
      interval: 15s
      timeout: 10s
      retries: 10
      # First boot creates the schema and can take minutes on a cold database.
      start_period: 600s

EOF
}

render::_agent() {
    local n=$1
    local privileged='' docker_env='' docker_vol=''

    # Mapped whenever the image declares it, not only under DinD — otherwise the
    # inner daemon's layers land in an anonymous volume and are re-pulled on
    # every recreate.
    render::_agent_has_docker_volume && docker_vol=$'\n'"      - agent-${n}-docker:/var/lib/docker"

    case $TC_AGENT_DOCKER in
        dind)
            privileged=$'    privileged: true\n'
            docker_env=$'      DOCKER_IN_DOCKER: start\n'
            ;;
        socket)
            docker_vol="$docker_vol"$'\n'"      - /var/run/docker.sock:/var/run/docker.sock"
            ;;
    esac

    cat <<EOF
  agent-$n:
    image: $(conf::agent_tag)
    restart: unless-stopped
    depends_on:
      # service_started, not service_healthy: the server's first boot builds the
      # schema and can outlast any sane health timeout. Agents retry their own
      # connection quite happily, so gating them on health only delays them.
      server:
        condition: service_started
${privileged}    environment:
      # The in-network address, never the browser-facing URL. Pointing an agent
      # at http://localhost:8111 is the single most common way to end up with an
      # agent that will not connect.
      SERVER_URL: http://server:8111
      AGENT_NAME: ${TC_STACK}-agent-$n
      OWN_ADDRESS: ${TC_STACK}-agent-$n
      # Matching the server's teamcity.agentAutoAuthorize.authorizationToken, so
      # the agent authorizes itself instead of waiting in the Unauthorized list.
      AGENT_TOKEN: \${TC_AGENT_AUTH_TOKEN}
      # The agent image hardcodes TZ=Europe/London; without this every build
      # timestamp is wrong for anyone outside that zone.
      TZ: \${TC_TZ}
${docker_env}    volumes:
$(render::_volume_lines TC_AGENT_VOLUMES "agent-$n-")$docker_vol

EOF
}

# render::_volume_lines <array-name> <volume-name-prefix>
render::_volume_lines() {
    local -n spec=$1
    local prefix=$2
    local entry name path
    for entry in "${spec[@]}"; do
        name=${entry%%:*}
        path=${entry#*:}
        printf '      - %s%s:%s\n' "$prefix" "$name" "$path"
    done
}

render::_volumes() {
    printf 'volumes:\n'

    local entry
    for entry in "${TC_SERVER_VOLUMES[@]}"; do
        printf '  %s:\n' "${entry%%:*}"
    done

    if [[ $TC_DB == postgres ]]; then
        printf '  pgdata:\n'
        printf '  jdbc-cache:\n'
    fi

    local n
    for (( n = 1; n <= TC_AGENTS; n++ )); do
        for entry in "${TC_AGENT_VOLUMES[@]}"; do
            printf '  agent-%s-%s:\n' "$n" "${entry%%:*}"
        done
        # if, not &&: a false && as the last statement in the loop would make
        # this function return non-zero and abort the render under set -e.
        if render::_agent_has_docker_volume; then
            printf '  agent-%s-docker:\n' "$n"
        fi
    done
}

# Every volume this stack owns, as the daemon names them.
render::volume_names() {
    local entry n
    for entry in "${TC_SERVER_VOLUMES[@]}"; do printf '%s_%s\n' "$TC_STACK" "${entry%%:*}"; done
    if [[ $TC_DB == postgres ]]; then
        printf '%s_pgdata\n%s_jdbc-cache\n' "$TC_STACK" "$TC_STACK"
    fi
    for (( n = 1; n <= TC_AGENTS; n++ )); do
        for entry in "${TC_AGENT_VOLUMES[@]}"; do
            printf '%s_agent-%s-%s\n' "$TC_STACK" "$n" "${entry%%:*}"
        done
        if render::_agent_has_docker_volume; then
            printf '%s_agent-%s-docker\n' "$TC_STACK" "$n"
        fi
    done
}
